* Bokbase

This is a webapp that implements a simple book database intended to create goodreads-compatible csv files for use in [[https://bookwyrm.social/import][imports to bookwyrm]].

Data storage is in a PostgreSQL database and there is a simple react.js GUI to edit books, import calibre metadata, and export [[https://zief0002.github.io/epsy-8251/codebooks/goodreads.html][goodreads style CSV files]].

To give users access to the database, add the [[https://shiro.apache.org/authorization.html#Authorization-Roles][shiro role]] bokbaseuser to the user in [[https://github.com/steinarb/authservice][authservice]].

** Development status
[[https://travis-ci.org/steinarb/bokbase][file:https://travis-ci.org/steinarb/bokbase.svg?branch=master]]

** Installing the bokbase application

Here are the instructions for how to run bokbase locally:
 1. Install a PostgreSQL database server locally, use e.g. an .msi installer on Windows or APT on debian
 2. Add a PostgreSQL user named karaf, with password karaf, either using pgadmin or from the command line:
    #+begin_example
      /usr/bin/sudo -u postgres createuser karaf
    #+end_example
 3. Add a blank database named authservice, with owner "karaf", either using pgadmin or from the command line:
    #+begin_example
      /usr/bin/sudo -u postgres createdb -O karaf authservice
    #+end_example
 4. Add a blank database named bokbase, with owner "karaf", either using pgadmin or from the command line:
    #+begin_example
      /usr/bin/sudo -u postgres createdb -O karaf bokbase
    #+end_example
 5. Clone and build bokbase
    #+begin_example
      mkdir -p ~/git
      cd ~/git/
      git clone https://github.com/steinarb/bokbase.git
      cd bokbase
      mvn clean install
    #+end_example
 6. Download and start apache karaf (see the [[https://karaf.apache.org/manual/latest/quick-start.html][karaf quick start guide]])
 7. From the karaf command line, install bokbase:
    #+begin_example
      feature:repo-add mvn:no.priv.bang.bokbase/karaf/LATEST/xml/features
      feature:install bokbase-with-postgresql
    #+end_example
 8. Open http://localhost:8181/authservice/useradmin in a web browser and log in as user admin, password admin
 9. Create a user for yourself with the role "bokbaseuser"
 10. Open http://localhost:8181/bokbase in a web browser and log with the username and password of the user created above
 11. Add some users and books and try exporting a CSV file
 12. Try importing the file into goodwyrm

Running PostgreSQL on a different server and with a different username and password is possible with configuration.

Installing karaf more permanently than what is done in the quick start guide (which is downloading and unpacking a tarball or a zip file, and running a command found in the unpacked directory) is also possible.

** Installing test version of the bokbase application

This version uses an in-memory derby dataset with an initial (small) dataset.

Give the following commands to the karaf console:
#+BEGIN_EXAMPLE
  feature:repo-add mvn:no.priv.bang.bokbase/karaf/LATEST/xml/features
  feature:install bokbase-with-derby
#+END_EXAMPLE
** Configuring a new default locale

Out of the box, the sample application supports two locales: nb_NO (Norwegian bokmål) and en_GB (UK English).

The locale texts are provided by a Java resource bundle, and new languages can be added by adding them to the bundle and to the available locales returned by the BokbaseService.

The default locale is nb_NO.

It is possible to persistently configuring the default locale to en_GB with the following commands in the karaf console command line:
#+begin_example
  config:edit no.priv.bang.bokbase.backend.BokbaseServiceProvider
  config:property-set defaultlocale en_GB
  config:update
#+end_example

/Note/! The name of the config file will change when the package name and classname of the class changes in a new application based on this one, so adjust the command example accordingly.
** License

This software is licensed with the Apache License v2.  See the file LICENSE for details.
